from .leboncoin import LeboncoinScraper
from .seloger import SelogerScraper
from .lefigaro import LeFigaroScraper
from .logicimmo import LogicimmoScraper
from .bienici import BieniciScraper
from .iadfrance import IadfranceScraper
from .notaires import NotairesScraper
from .vinci import VinciScraper
from .immobilier_france import ImmobilierFranceScraper
